const Job = require('./models/Job');
const User = require('./models/User');

const sampleJobs = [
  {
    title: 'Senior Frontend Engineer',
    company: 'Google',
    location: 'Mountain View, CA',
    type: 'Full-Time',
    category: 'Technology',
    salary: '$140K – $180K / yr',
    salaryMin: 140000,
    salaryMax: 180000,
    description: 'Join Google\'s world-class engineering team to build products used by billions. You\'ll work on cutting-edge web technologies, collaborate with brilliant minds, and shape the future of the internet.',
    requirements: ['5+ years React/Vue/Angular experience', 'Strong TypeScript & JavaScript skills', 'Experience with performance optimization', 'BS/MS in Computer Science or equivalent'],
    responsibilities: ['Lead frontend architecture decisions', 'Mentor junior engineers', 'Collaborate with designers and PMs', 'Drive code quality and testing standards'],
    skills: ['React', 'TypeScript', 'GraphQL', 'Performance', 'Testing'],
    experience: '5+ years',
    companyLogo: 'G',
    companyColor: 'linear-gradient(135deg, #4285F4, #34A853)',
    featured: true,
    remote: false,
    applicantsCount: 234,
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Full Stack Developer',
    company: 'Stripe',
    location: 'Remote',
    type: 'Remote',
    category: 'Technology',
    salary: '$120K – $160K / yr',
    salaryMin: 120000,
    salaryMax: 160000,
    description: 'Build the financial infrastructure for the internet. Work on Stripe\'s core payment APIs and developer tools that power millions of businesses worldwide.',
    requirements: ['3+ years Node.js & React experience', 'Experience with distributed systems', 'Strong problem-solving skills', 'API design experience'],
    responsibilities: ['Design and build scalable APIs', 'Improve developer experience', 'Ship features end-to-end', 'Participate in on-call rotation'],
    skills: ['Node.js', 'React', 'PostgreSQL', 'Redis', 'AWS'],
    experience: '3+ years',
    companyLogo: 'S',
    companyColor: 'linear-gradient(135deg, #635BFF, #80E9FF)',
    featured: true,
    remote: true,
    applicantsCount: 187,
    deadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'UI/UX Designer',
    company: 'Meta',
    location: 'Menlo Park, CA',
    type: 'Full-Time',
    category: 'Design',
    salary: '$130K – $170K / yr',
    salaryMin: 130000,
    salaryMax: 170000,
    description: 'Design the next generation of social experiences for billions of people. Work across Facebook, Instagram, WhatsApp to create intuitive, beautiful, and accessible interfaces.',
    requirements: ['4+ years UI/UX design experience', 'Proficiency in Figma & Prototyping', 'Portfolio demonstrating impact', 'Strong user research skills'],
    responsibilities: ['Lead design for major product features', 'Run user research studies', 'Create and maintain design systems', 'Present designs to senior leadership'],
    skills: ['Figma', 'Prototyping', 'User Research', 'Design Systems', 'Accessibility'],
    experience: '4+ years',
    companyLogo: 'M',
    companyColor: 'linear-gradient(135deg, #1877F2, #42B72A)',
    featured: true,
    remote: false,
    applicantsCount: 156,
    deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Data Scientist',
    company: 'Netflix',
    location: 'Los Gatos, CA',
    type: 'Full-Time',
    category: 'Technology',
    salary: '$150K – $200K / yr',
    salaryMin: 150000,
    salaryMax: 200000,
    description: 'Use data to shape what 230M+ people watch every day. Build recommendation systems, analyze viewing patterns, and influence product decisions with rigorous data science.',
    requirements: ['PhD or MS in Statistics, ML, or related field', 'Expert in Python & R', 'Experience with large-scale ML systems', 'Strong experimentation methodology'],
    responsibilities: ['Build content recommendation models', 'Design and analyze A/B tests', 'Work with engineering to deploy models', 'Communicate insights to executives'],
    skills: ['Python', 'Machine Learning', 'Spark', 'Statistics', 'SQL'],
    experience: '4+ years',
    companyLogo: 'N',
    companyColor: 'linear-gradient(135deg, #E31837, #000)',
    featured: false,
    remote: false,
    applicantsCount: 89,
    deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'DevOps Engineer',
    company: 'Amazon',
    location: 'Seattle, WA',
    type: 'Full-Time',
    category: 'Technology',
    salary: '$130K – $175K / yr',
    salaryMin: 130000,
    salaryMax: 175000,
    description: 'Build and maintain the infrastructure that powers Amazon\'s global services. You\'ll work on automation, reliability, and scaling systems that handle millions of requests per second.',
    requirements: ['3+ years DevOps/SRE experience', 'Strong AWS & Kubernetes knowledge', 'CI/CD pipeline expertise', 'Infrastructure-as-code (Terraform)'],
    responsibilities: ['Design cloud infrastructure', 'Automate deployment pipelines', 'Monitor and improve system reliability', 'Lead incident response'],
    skills: ['AWS', 'Kubernetes', 'Docker', 'Terraform', 'Python'],
    experience: '3+ years',
    companyLogo: 'A',
    companyColor: 'linear-gradient(135deg, #FF9900, #146EB4)',
    featured: false,
    remote: false,
    applicantsCount: 112,
    urgent: true,
    deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Product Manager',
    company: 'Spotify',
    location: 'New York, NY',
    type: 'Full-Time',
    category: 'Technology',
    salary: '$125K – $165K / yr',
    salaryMin: 125000,
    salaryMax: 165000,
    description: 'Define the future of music and podcast discovery. Lead cross-functional teams to build features that delight Spotify\'s 500M+ users globally.',
    requirements: ['4+ years PM experience', 'Strong analytical skills', 'Experience with consumer products', 'Excellent communication skills'],
    responsibilities: ['Define product vision and roadmap', 'Collaborate with engineering and design', 'Analyze metrics and user feedback', 'Drive go-to-market strategy'],
    skills: ['Product Strategy', 'Analytics', 'Agile', 'User Research', 'Roadmapping'],
    experience: '4+ years',
    companyLogo: 'S',
    companyColor: 'linear-gradient(135deg, #1DB954, #191414)',
    featured: true,
    remote: false,
    applicantsCount: 203,
    deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Marketing Manager',
    company: 'HubSpot',
    location: 'Remote',
    type: 'Remote',
    category: 'Marketing',
    salary: '$90K – $120K / yr',
    salaryMin: 90000,
    salaryMax: 120000,
    description: 'Drive growth for HubSpot\'s CRM platform. Lead integrated marketing campaigns, manage content strategy, and own key demand generation metrics.',
    requirements: ['3+ years B2B marketing experience', 'Data-driven mindset', 'Experience with marketing automation', 'Strong writing and communication skills'],
    responsibilities: ['Plan and execute marketing campaigns', 'Manage content calendar', 'Report on marketing metrics', 'Collaborate with sales team'],
    skills: ['Content Marketing', 'SEO', 'HubSpot', 'Analytics', 'Copywriting'],
    experience: '3+ years',
    companyLogo: 'H',
    companyColor: 'linear-gradient(135deg, #FF7A59, #FF5C35)',
    featured: false,
    remote: true,
    applicantsCount: 67,
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Financial Analyst',
    company: 'Goldman Sachs',
    location: 'New York, NY',
    type: 'Full-Time',
    category: 'Finance',
    salary: '$100K – $140K / yr',
    salaryMin: 100000,
    salaryMax: 140000,
    description: 'Join the world\'s leading investment bank\'s analytics team. Work on complex financial models, support M&A transactions, and provide insights that drive billion-dollar decisions.',
    requirements: ['BS/MS in Finance, Economics, or related', '2+ years financial analysis experience', 'Advanced Excel & financial modeling', 'CFA preferred'],
    responsibilities: ['Build and maintain financial models', 'Conduct industry and competitor research', 'Support deal teams with analysis', 'Present findings to senior bankers'],
    skills: ['Financial Modeling', 'Excel', 'Valuation', 'Bloomberg', 'Python'],
    experience: '2+ years',
    companyLogo: 'GS',
    companyColor: 'linear-gradient(135deg, #0A3161, #4B8BBE)',
    featured: false,
    remote: false,
    applicantsCount: 145,
    deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Software Engineer Intern',
    company: 'Microsoft',
    location: 'Redmond, WA',
    type: 'Internship',
    category: 'Technology',
    salary: '$45 / hr',
    salaryMin: 45,
    salaryMax: 55,
    description: 'Join Microsoft\'s internship program and work on real products used by millions. Gain hands-on experience with cloud, AI, and developer tools in a collaborative environment.',
    requirements: ['Pursuing BS/MS in Computer Science', 'Strong programming fundamentals', 'Experience in any major language', 'Enrolled in accredited university'],
    responsibilities: ['Complete defined project with mentor guidance', 'Present project to team at end of internship', 'Participate in intern events', 'Contribute to codebase'],
    skills: ['Python', 'Java', 'C++', 'Azure', 'Git'],
    experience: 'Student / Entry level',
    companyLogo: 'MS',
    companyColor: 'linear-gradient(135deg, #00A4EF, #7FBA00)',
    featured: false,
    remote: false,
    applicantsCount: 523,
    urgent: true,
    deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Healthcare Data Analyst',
    company: 'UnitedHealth Group',
    location: 'Minneapolis, MN',
    type: 'Full-Time',
    category: 'Healthcare',
    salary: '$75K – $95K / yr',
    salaryMin: 75000,
    salaryMax: 95000,
    description: 'Analyze healthcare data to improve patient outcomes and reduce costs. Use data science to uncover actionable insights across millions of patient records.',
    requirements: ['Healthcare industry experience preferred', 'Strong SQL and Python skills', 'HIPAA compliance knowledge', 'BI tools experience (Tableau, Power BI)'],
    responsibilities: ['Analyze claims and clinical data', 'Build dashboards for stakeholders', 'Support population health initiatives', 'Ensure data privacy compliance'],
    skills: ['SQL', 'Python', 'Tableau', 'Healthcare Analytics', 'HIPAA'],
    experience: '2+ years',
    companyLogo: 'UH',
    companyColor: 'linear-gradient(135deg, #007AB8, #009DD9)',
    featured: false,
    remote: false,
    applicantsCount: 78,
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Mechanical Engineer',
    company: 'Tesla',
    location: 'Fremont, CA',
    type: 'Full-Time',
    category: 'Engineering',
    salary: '$110K – $145K / yr',
    salaryMin: 110000,
    salaryMax: 145000,
    description: 'Help design and manufacture the world\'s most innovative electric vehicles. Work on everything from Model 3 to Cybertruck, solving complex engineering challenges at scale.',
    requirements: ['BS/MS in Mechanical Engineering', '3+ years automotive or manufacturing experience', 'CAD proficiency (CATIA, SolidWorks)', 'Experience with GD&T'],
    responsibilities: ['Design mechanical components for EVs', 'Lead DFM/DFA reviews', 'Collaborate with manufacturing teams', 'Drive cost reduction initiatives'],
    skills: ['SolidWorks', 'CATIA', 'GD&T', 'FEA', 'Manufacturing'],
    experience: '3+ years',
    companyLogo: 'T',
    companyColor: 'linear-gradient(135deg, #E31937, #CC0000)',
    featured: false,
    remote: false,
    applicantsCount: 201,
    deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Sales Executive',
    company: 'Salesforce',
    location: 'San Francisco, CA',
    type: 'Full-Time',
    category: 'Sales',
    salary: '$80K base + commissions',
    salaryMin: 80000,
    salaryMax: 150000,
    description: 'Drive enterprise sales for the world\'s #1 CRM. Build relationships with Fortune 500 companies, demonstrate Salesforce\'s value, and exceed ambitious revenue targets.',
    requirements: ['3+ years B2B enterprise sales experience', 'Proven track record of quota attainment', 'Strong CRM and SaaS knowledge', 'Excellent presentation skills'],
    responsibilities: ['Manage full sales cycle for enterprise accounts', 'Build and maintain C-suite relationships', 'Exceed quarterly sales quotas', 'Develop account strategy and plans'],
    skills: ['Enterprise Sales', 'Salesforce CRM', 'Negotiation', 'Solution Selling', 'Forecasting'],
    experience: '3+ years',
    companyLogo: 'SF',
    companyColor: 'linear-gradient(135deg, #00A1E0, #0D9DDA)',
    featured: false,
    remote: false,
    applicantsCount: 94,
    deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
  },
];

async function seedJobs() {
  try {
    // Create an admin user first
    let adminUser = await User.findOne({ email: 'admin@nexajobs.com' });
    if (!adminUser) {
      adminUser = new User({
        name: 'Admin',
        email: 'admin@nexajobs.com',
        password: 'admin123',
        role: 'admin',
      });
      await adminUser.save();
      console.log('👑 Admin user created: admin@nexajobs.com / admin123');
    }

    const jobsWithUser = sampleJobs.map(job => ({ ...job, postedBy: adminUser._id }));
    await Job.insertMany(jobsWithUser);
    console.log(`✅ Seeded ${sampleJobs.length} sample jobs`);
  } catch (err) {
    console.error('❌ Seed error:', err.message);
  }
}

// Run directly: node seed.js
if (require.main === module) {
  const mongoose = require('mongoose');
  require('dotenv').config();
  mongoose.connect(process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/nexajobs')
    .then(async () => {
      console.log('Connected to MongoDB');
      await Job.deleteMany({});
      await User.deleteMany({});
      await seedJobs();
      console.log('✅ Done!');
      process.exit(0);
    })
    .catch(err => { console.error(err); process.exit(1); });
}

module.exports = { seedJobs };
